### ISSUE TITLE
电脑驱动问题

### ISSUE THREAD

**Issue by haoqing-yan** [NiiiKlaus/Get-my-Arch-Linux#10]
电脑要安装驱动，有那些软件推荐？还有笔记本触摸板的驱动，还有一些声卡驱动怎么解决啊？我在网上搜索 alsa 可以解决声卡驱动的，但我驱动还是找不到声卡有声卡驱动的列表吗？

**Comment by NiiiKlaus** [comment]
你好，你提到了触摸板和声卡，这两者之间是有一定区别的。从我个人的经历而言，我手边有一台笔记本，不算太新，它的触摸板和声卡可以直接免驱运行（也可能是Linux内核中已经包含了它们对应的驱动，我这里的“免驱”指的是不需要额外安装特定的包就可以运行），但是在显卡（Intel集成显卡）方面出现过问题（不安装驱动的话会出现垂直不同步和对角线撕裂，安装驱动`sudo pacman -S xf86-video-intel`之后解决）。这里和你分享一下，如果你也遇到类似的问题，给你提供一个参考。
言归正传，触摸板和声卡之所以会有区别，是因为触摸板是否正常工作你只会在启动图形界面之后才发现，而声卡是否正常工作在`tty`界面下就可以发现。如果你没有关闭警报声的话，在`tty`界面下进入控制台，不输入任何东西，一直点按<kbd>Backspace</kbd>，你应该会听到“哔哔哔哔”的声音。如果听到的话，那说明声卡是正常的，或者至少`tty`下可用。
Arch Linux的软件仓库中有一个叫做`xorg-drivers`的组，里面是`Xorg`的驱动：
```bash
➜  ~ sudo pacman -Sgq xorg-drivers
xf86-input-evdev
xf86-input-libinput
xf86-input-synaptics
xf86-input-vmmouse
xf86-input-void
xf86-video-amdgpu
xf86-video-ati
xf86-video-dummy
xf86-video-fbdev
xf86-video-intel
xf86-video-nouveau
xf86-video-openchrome
xf86-video-vesa
xf86-video-vmware
xf86-video-voodoo
xf86-video-qxl
```
中间是`input`的是输入设备，`video`是显示设备。对于你的触摸板（输入设备），如果你懒得弄清楚到底装这个组里的哪一个，就直接安装整个组好了（不大，就4、5M），安装完成后记得重启。重启后，如果你的触摸板能用了，那最好，如果不能用的话，我能力有限，也想不出什么其他的办法了。至于声卡驱动，我因为没有遇到过这方面的问题，所以也没做过研究，很抱歉帮不上什么忙。如果有时间的话，你可以再做一些功课。如果解决了的话，欢迎在这里分享你的解决方法。
有一个潜在的解决方法，我个人不是很喜欢，不过确实可以解决问题。你可以去你笔记本厂商的官网上寻找你对应机型的硬件驱动，不过找到的可能性不大，因为现在大多的厂商只提供了Windows下的驱动，Linux下的驱动鲜有适配。如果有Linux下的驱动的话，那八成可以解决问题（不过这些驱动大部分都是闭源的，你可能找不到或者找不全它安装了一些什么东西以及安装在哪里，我个人不太喜欢）。
如果以上都没有解决问题的话，你也可以自己写驱动，当然这十分的hacky，不过应该不是特别难，我身边有朋友成功过，不过我没去做了解。可以在搜索引擎里搜索一下有没有人做过相关的教程分享。如果你成功了，欢迎你与大家一起分享整个过程。
在遇到问题的时候，在ArchWiki里搜索关键字可能比更有针对性，如果你没有尝试过的话，我建议你再根据[ArchWiki](https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture)里的指导进行一下操作。另外，根据[这篇博客](https://itstillworks.com/install-sound-card-linux-5038629.html)，Linux下大部分的声卡都是开箱即用的（我的体验也证明了这一点，我一直使用的都是`Arch To Go`，目前还没有遇到过声卡不好用的情况），有可能你的声卡已经正常工作，但它默认情况下是静音的，可能你没有发现，注意留个心眼儿。

**Comment by haoqing-yan** [comment]
我按照你给的仓库安装了驱动，触摸板是没什么问题了；但是安装声卡还是没有找到 
```aplay: device_list:2774: no soundcards found```
我安装的设备为 ![设备](https://github.com/yanwenjun98/comment/blob/master/picture/desktop.png)
 与他的设备一样的 @theniceboy
