### ISSUE TITLE
安装xrog问题

### ISSUE THREAD

**Issue by shuixiaomo** [NiiiKlaus/Get-my-Arch-Linux#5]
![Screenshot_20200214_211801_com android chrome](https://user-images.githubusercontent.com/22076302/74534932-c4cdb080-4f6f-11ea-8b82-ebc651aca195.jpg)
我下载的没有xin

**Comment by shuixiaomo** [comment]
使用命令 sudo pacman -S xorg 
没有找到xinit下的 xinitrc ,只有文件夹 xinitrc.d

**Comment by SpringHan** [comment]
你的详细xinit.d详细路径请提供一下

**Comment by shuixiaomo** [comment]
![IMG_20200214_214416](https://user-images.githubusercontent.com/22076302/74536508-322f1080-4f73-11ea-9bb1-7f3c84cdb17d.jpg)

**Comment by SpringHan** [comment]
那个，我现在在手机端网络不好，看不见图片，您能否把路径用文字发出来，或者我明天用电脑看

**Comment by shuixiaomo** [comment]
/etc/X11/xinit

**Comment by shuixiaomo** [comment]
/xinitrc.d/50-system-user.sh
我的是这样的

**Comment by SpringHan** [comment]
那您安装了xorg-xinit了吗?

**Comment by shuixiaomo** [comment]
没有，sudo pacman -S xorg  我只执行了这个命令

**Comment by SpringHan** [comment]
您可以使用
```bash
sudo pacman -Q xorg-xinit
```
来检查一下，如果没有输出，则没有安装，安装一下之后就应该生成了xinitrc文件了

**Comment by shuixiaomo** [comment]
好了，谢谢大佬
