### ISSUE TITLE
按照官方文档给ASUS flip c100p安装archlinux，arm的，各种问题，麻烦大佬帮忙看下

### ISSUE THREAD

**Issue by evilRat** [NiiiKlaus/Get-my-Arch-Linux#6]
![2020-03-13 03 21 08](https://user-images.githubusercontent.com/10190423/76559256-cd1afc00-64d9-11ea-868e-02e044c19a4f.jpg)
![2020-03-13 03 22 18](https://user-images.githubusercontent.com/10190423/76559303-df953580-64d9-11ea-9a0b-ec61416410bf.jpg)
![2020-03-13 03 22 32](https://user-images.githubusercontent.com/10190423/76559319-e58b1680-64d9-11ea-9c54-f08a33ff803b.jpg)

**Comment by NiiiKlaus** [comment]
重装一下吧，这个我也不是很清楚，不好意思。

**Comment by NiiiKlaus** [comment]
https://archlinuxarm.org/platforms/armv7/rockchip/asus-chromebook-flip-c100p
看看有没有什么帮助。

**Comment by NiiiKlaus** [comment]
长时间无回应，关闭此issue，有需要请再打开。
